config/routes.rb
RailsTweetApp::Application.routes.draw do

  
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'login' => 'sessions#new', :as => :login
  match 'login' => 'sessions#create', :via => :post
  resources :authors
  resources :editors

  root :to => 'home#index'
  

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  before_filter { |f| f.user_has_perm? 'author' }

  def index
  end

  def new
    @tweet = Tweet.new
  end

  def edit
    @tweet = Tweet.find(params[:id])

    if @tweet.for_editors || @tweet.author != @current_user || !@tweet.twitter_id.nil?
      redirect_to authors_url, :alert => "You do not have access to edit this tweet."
    end
  end
  # {{{ def create
  def create
    begin
      params[:tweet][:tweet] = Correction.autocorrect_all(params[:tweet][:tweet])
      params[:tweet][:author] = @current_user
      @tweet = Tweet.new(params[:tweet])

      if @tweet.save
        notice = 'Post saved'

        if params[:commit] == 'Publish'

          if @tweet.moderate?
            notice += ' and moderated...'
          elsif @tweet.publish?
            notice += ' and published...'
          end

          @tweet.save
        end

        redirect_to authors_url, :notice => notice
      else
        render 'new'
      end

    rescue ActiveRecord::RecordNotFound
      flash.now.alert = 'Author was not found when creating tweet'
      redirect_to root_url
    end
  end
  # }}}
  # {{{ def update
  def update
    @tweet = Tweet.find(params[:id])

    if @tweet.for_editors || @tweet.author != @current_user || !@tweet.twitter_id.nil?
      redirect_to authors_url, :alert => "You do not have access to edit this tweet."
    end

    params[:tweet][:author] = @current_user
    params[:tweet][:tweet] = Correction.autocorrect_all(params[:tweet][:tweet])

    if @tweet.update_attributes(params[:tweet])
      notice = 'Post saved'
      if params[:commit] == 'Publish'
        if @tweet.moderate?
          notice += ' and moderated...'
        elsif @tweet.publish?
          notice += ' and published...'
        end
        @tweet.save
      end
      redirect_to authors_path, :notice => notice
    end
  end
  # }}}

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/edit.html.erb
<h1>Edit Tweet</h1>

<%= form_for @tweet, :url => author_path do |f| %>
  <% if @tweet.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @tweet.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field"><%= f.label :tweet %> <%= f.text_area :tweet %></div>
  <div class="field"><%= f.submit %></div>
  <div class="field"><%= f.submit "Publish" %></div>
  <%= link_to 'My Tweets', authors_path %>
<% end %>

app/views/authors/index.html.erb
<h1>Tweets</h1>
<p class="notice"><%= flash[:notice] %></p>
<p class="alert"><%= flash[:alert] %></p>
<h2>My Tweets</h2>
<ul>
  <% @current_user.authored_tweets.each do |t| %>
    <% if !t.for_editors && t.twitter_id.nil? %>
      <li><a href="<%= edit_author_path(t) %>"><%= t.tweet %></a></li>
    <% end %>
  <% end %>
</ul>

<p><a href="<%= new_author_path %>">New Tweet</a></p>

app/views/authors/new.html.erb
<h1>New Tweet</h1>

<%= form_for @tweet, :url => authors_path do |f| %>
  <% if @tweet.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @tweet.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field"><%= f.label :tweet %> <%= f.text_area :tweet %></div>
  <div class="field"><%= f.submit %></div>
  <div class="field"><%= f.submit "Publish" %></div>
  <%= link_to 'My Tweets', authors_path %>
<% end %>