config/routes.rb
RailsTweetApp::Application.routes.draw do

  
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'login' => 'sessions#new', :as => :login
  match 'login' => 'sessions#create', :via => :post
  resources :authors
  resources :editors

  root :to => 'home#index'
  

end

app/controllers/editors_controller.rb
class EditorsController < ApplicationController

  before_filter { |f| f.user_has_perm? 'editor' }

  def index
  end

  def edit
    @tweet = Tweet.find(params[:id])

    unless @tweet.for_editors && @tweet.twitter_id.nil?
      redirect_to authors_url, :alert => "You do not have access to edit this tweet."
    end
  end
  # {{{ def update
  def update
    @tweet = Tweet.find(params[:id])

    unless @tweet.for_editors && @tweet.twitter_id.nil?
      redirect_to authors_url, :alert => "You do not have access to edit this tweet."
    end

    params[:tweet][:editor] = @current_user
    params[:tweet][:tweet] = Correction.autocorrect_all(params[:tweet][:tweet])

    if @tweet.update_attributes(params[:tweet])
      notice = 'Post saved'
      if params[:commit] == 'Publish'
        if @tweet.moderate?
          notice += ' and moderated...'
        elsif @tweet.publish?
          notice += ' and published...'
        end
        @tweet.save
      end
      redirect_to authors_path, :notice => notice
    end
  end
  # }}}

end

app/helpers/editors_helper.rb
module EditorsHelper
end

app/views/editors/edit.html.erb
<h1>Edit Tweet</h1>

<%= form_for @tweet, :url => editor_path do |f| %>
  <% if @tweet.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @tweet.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field"><%= f.label :tweet %> <%= f.text_area :tweet %></div>
  <div class="field"><%= f.submit %></div>
  <div class="field"><%= f.submit "Publish" %></div>
  <%= link_to 'My Tweets', editors_path %>
<% end %>

app/views/editors/index.html.erb
<h1>Tweets</h1>
<p class="notice"><%= flash[:notice] %></p>
<p class="alert"><%= flash[:alert] %></p>

<h2>Moderated Tweets</h2>
<ul>
  <% Tweet.where(:for_editors => true, :twitter_id => nil, :needs_moderation => true).each do |t| %>
    <li><%= link_to t.tweet, edit_editor_path(t) %> Reason(s): <%= t.moderation_reasons.join(', ') %> Moderated: <%= t.moderation_date.strftime("%m/%d/%Y") %></li>
  <% end %>
</ul>

<h2>Tweeted Tweets</h2>
<ul>
  <% Tweet.where(Tweet.arel_table[:twitter_id].not_eq(nil)).each do |t| %>
    <li><%= t.tweet %> Retweet count: <%= t.retweet_count %></li>
  <% end %>
</ul>